## LogisticRegression
>Note:it is classification algorithm but internally uses linear model hence
name include Regression term.

>it also gives you probabilty regarding prediction.

In [3]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris

In [4]:
df=pd.read_csv("G:/dataset/classification/fruits.csv")
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values


In [5]:
model=LogisticRegression()
model.fit(X,y)

LogisticRegression()

In [6]:
sample=[3.5,40]
print(model.predict([sample]))
print(model.predict_proba([sample]))

['Banana']
[[0.16936411 0.83063589]]


In [7]:
df=load_iris()
X=df.data
y=df.target

model=LogisticRegression(max_iter=200)
model.fit(X,y)

LogisticRegression(max_iter=200)

In [8]:
print(model.predict_proba([[.7,.1,2.5,1.1]]))
print(model.predict([[.7,.1,2.5,1.1]]))

[[0.75331218 0.24299954 0.00368829]]
[0]


## maths behind LogisticRegression
- first it builds a linear model to find coefs and intercept
- then convert this linear model to non linear sothat it can perform classification.
- logit fun is used to convert linear part to non linear
- sigmoid & softmax are used as logit funs.
- with binary classification,sigmoid is used and with multiclass softmax is used.

## Binary Classification 

In [11]:
df=pd.read_csv("G:/dataset/classification/fruits.csv")
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values
model=LogisticRegression()
model.fit(X,y)


LogisticRegression()

In [12]:
model.coef_

array([[-0.98517568, -0.02200477]])

In [13]:
model.intercept_

array([5.91844611])

## Linear Part using code

In [15]:
sample=[3.5,40]
z=-0.98517568*3.5+-0.02200477*40+5.91844611
print(z)

1.59014043


In [18]:
print(model.decision_function([sample]))

[1.59014062]


## Non Linear Part using Sigmoid function (Logit Function)
- sigmoid func= 1/1+e^-z   ## this formula gives you probability of class 1 or +ve class.
- if you want to determine the probability of class 0 then
- sigmoid function= 1/1+e^z 

In [28]:
# Probability of class 1
result=1/(1+np.exp(-z))
print(result)
if result<=.5:
    print("Apple")
else:
    print("Banana")

0.8306358596656029
Banana


In [30]:
print(model.predict([sample]))
print(model.predict_proba([sample]))

['Banana']
[[0.16936411 0.83063589]]


In [32]:
# probability of class 0 
result=1/(1+np.exp(z))
print(result)

0.16936414033439706


In [34]:
# also you try 1-probabilitty of class 1
p_0=1-1/(1+np.exp(-z))
p_0

0.16936414033439706

## Multi Class Classification

## Multiclass classification used Softmax function to convert linear part into non linear part.
- there are two approach.
- 1. OVR (One vs Rest) --> in this we train multi model according to how many class in your dataset in this we let update +ve class in each model. Then used sigmoid to solve the multiclass problem.
- 2. Multinomial (softmax) --> in this we train each class separate model and the convert each model to non linear part and max of the probablity is our output

In [39]:
from sklearn.datasets import load_iris

## OVR 

In [42]:
df=load_iris()
X=df.data
y=df.target

model=LogisticRegression(multi_class='ovr',max_iter=200)
model.fit(X,y)

C:\Users\YADUV\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(max_iter=200, multi_class='ovr')

In [44]:
sample=[1.5,.8,3.5,.9]
print(model.predict([sample]))
print(model.predict_proba([sample]))

[1]
[[0.08312302 0.87525322 0.04162376]]


In [46]:
model.coef_

array([[-0.44565052,  0.90054581, -2.32023343, -0.98112874],
       [-0.17917535, -2.12878487,  0.69671839, -1.27500517],
       [-0.39270716, -0.51442952,  2.93064063,  2.41608802]])

In [48]:
model.intercept_

array([  6.68931554,   5.58592907, -14.43598319])

In [50]:
z0=-0.44565052*1.5+  0.90054581*.8+ -2.32023343*3.5+ -0.98112874*.9+6.68931554
z1=-0.17917535*1.5+ -2.12878487*.8 + 0.69671839*3.5+ -1.27500517*.9+ 5.58592907
z2=-0.39270716*1.5+ -0.51442952*.8+  2.93064063*3.5+  2.41608802*.9+-14.43598319
print([z0,z1,z2])

[-2.2625564629999984, 4.905147861, -3.0048661229999993]


In [52]:
model.decision_function([sample])

array([[-2.26255646,  4.90514787, -3.00486612]])

In [54]:
p0=1/(1+np.exp(-z0))
p1=1/(1+np.exp(-z1))
p2=1/(1+np.exp(-z2))

print([p0,p1,p2])

[0.09427185965968823, 0.9926461324110328, 0.047206521501534475]


In [56]:
# Normalized probability
pn0=p0/(p0+p1+p2)
pn1=p1/(p0+p1+p2)
pn2=p2/(p0+p1+p2)

print([pn0,pn1,pn2])

[0.08312302444001633, 0.8752532200229097, 0.04162375553707395]


In [58]:
print(model.predict_proba([sample]))

[[0.08312302 0.87525322 0.04162376]]


## Multinomial

In [61]:
df=load_iris()
X=df.data
y=df.target

model=LogisticRegression(multi_class='multinomial',max_iter=200)
model.fit(X,y)

C:\Users\YADUV\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(max_iter=200, multi_class='multinomial')

In [63]:
sample=[1.5,.8,3.5,.9]
print(model.predict([sample]))
print(model.predict_proba([sample]))

[1]
[[0.2512822  0.69734664 0.05137116]]


In [65]:
model.coef_

array([[-0.41962017,  0.96690033, -2.51934621, -1.08448699],
       [ 0.53107361, -0.31498782, -0.20238066, -0.94412374],
       [-0.11145345, -0.65191251,  2.72172688,  2.02861073]])

In [67]:
model.intercept_

array([  9.83859123,   2.22306076, -12.061652  ])

In [69]:
z0=-0.41962017*1.5+  0.96690033*.8+ -2.51934621*3.5+ -1.08448699*.9+  9.83859123
z1=0.53107361*1.5+ -0.31498782*.8+ -0.20238066*3.5+ -0.94412374*.9+2.22306076
z2=-0.11145345*1.5+ -0.65191251*.8+  2.72172688*3.5+  2.02861073*.9+-12.061652 

print([z0,z1,z2])

[0.18893121300000004, 1.209637243, -1.3985684460000005]


In [71]:
model.decision_function([sample])

array([[ 0.18893121,  1.20963724, -1.39856845]])

In [73]:
p0=np.exp(z0)/(np.exp(z0)+np.exp(z1)+np.exp(z2))
p1=np.exp(z1)/(np.exp(z0)+np.exp(z1)+np.exp(z2))
p2=np.exp(z2)/(np.exp(z0)+np.exp(z1)+np.exp(z2))

print([p0,p1,p2])

[0.251282195843773, 0.6973466436770286, 0.05137116047919832]


In [75]:
model.predict_proba([sample])

array([[0.2512822 , 0.69734664, 0.05137116]])

In [77]:
print(model.predict([sample]))

[1]


In [79]:
import sklearn
sklearn.__version__

'1.5.1'

In [81]:
pd.__version__

'2.2.2'

In [83]:
np.__version__

'1.26.4'