## Computer Vision 

## Computer Vision is used to preprocess image and video for model Training.

In [1]:
import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt

## cv.resize is used to resize an image that take two argument (img,(width,height))

In [3]:
img=cv.imread('img.jpg')
img=cv.resize(img,(600,600))
cv.imshow('clr',img)
cv.waitKey(10000)
cv.destroyAllWindows()

In [4]:
img1=cv.imread('img.jpg')
img1=cv.resize(img1,(400,400))

## cv.flip is used to flip the image into three
- 1. Horizontal flip(mirror)
- 2. verticle flip (mirror)
- 3. both horizontal & vertical used 
(0,-1,1)

In [7]:
cv.imshow('img1',img1)
img2=cv.flip(img1,-1)
cv.imshow('img2',img2)
img3=cv.flip(img1,0)
cv.imshow('img3',img3)
img4=cv.flip(img1,1)
cv.imshow('img4',img4)
cv.waitKey(5000)
cv.destroyAllWindows()

## cv.split() is used to split channels 

In [9]:
img1=cv.imread('img.jpg')
b,g,r=cv.split(img1)
print('Blue channel array\n',b)
print('=========================================================')
print('Green channel array\n',g)
print('=========================================================')
print('Red channel array\n',r)

Blue channel array
 [[205 206 206 ... 208 208 208]
 [205 206 206 ... 208 208 208]
 [205 206 206 ... 208 208 208]
 ...
 [111 116 125 ...  37  37  37]
 [116 120 128 ...  38  39  39]
 [119 123 130 ...  39  39  39]]
Green channel array
 [[183 184 184 ... 187 187 187]
 [183 184 184 ... 187 187 187]
 [183 184 184 ... 187 187 187]
 ...
 [133 138 147 ...  45  45  45]
 [138 142 150 ...  46  47  47]
 [141 145 152 ...  47  47  47]]
Red channel array
 [[165 166 166 ... 156 156 156]
 [165 166 166 ... 156 156 156]
 [165 166 166 ... 156 156 156]
 ...
 [138 143 152 ...  52  52  52]
 [143 147 155 ...  53  54  54]
 [146 150 157 ...  54  54  54]]


In [22]:
img=cv.imread('img.jpg')
img=cv.resize(img,(400,400))

## cv.convertScaleAbs is used to increase contrast and brightness of an image where alpha is used to increase contrast and beta is used to increase brightness.

In [43]:
cv.imshow('img',img)
img1=cv.convertScaleAbs(img,alpha=2) #contrast
cv.imshow('img1',img1)
cv.waitKey(5000)
cv.destroyAllWindows()

In [67]:
img=cv.imread('img.jpg')
img=cv.resize(img,(400,400))

In [86]:
cv.imshow('img',img)
img1=cv.convertScaleAbs(img,beta=-15) #Brightness
cv.imwrite('pawanimg.jpg',img1)
cv.imshow('img1',img1)
cv.waitKey(5000)
cv.destroyAllWindows()

In [125]:
img=cv.imread('img.jpg')
img=cv.resize(img,(600,600))

## cv.line is used to draw liine into image
## cv.rectangle is used to draw rectangle into image
## cv.putText is used to write anything on the image

In [128]:
line=cv.line(img,(150,30),(350,30),(0,0,255),2)
cv.imshow('line',line)
cv.waitKey(5000)
cv.destroyAllWindows()

In [339]:
img=cv.imread('img.jpg')
img=cv.resize(img,(600,600))

In [342]:
rectangle=cv.rectangle(img,(170,35),(330,200),(0,0,255),2)
cv.circle(rectangle,(330,450),(95),(0,0,255),2)
cv.putText(rectangle,'Pawan Yadav',(350,45),cv.FONT_HERSHEY_PLAIN,2,(0,0,255),2)
cv.imshow('rectangle',rectangle)
cv.waitKey(5000)
cv.destroyAllWindows()