In [1]:
import torch
print((torch.__version__))

2.6.0+cu124


In [2]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available")

GPU is available
Using GPU: Tesla T4


## Creating a Tensor.

In [28]:
# Using empty:-  returns a tensor of the specified shape without initializing its values. The values in the returned tensor are whatever happens to already exist at that memory location (i.e., random "garbage" values).
a=torch.empty(2,3)
a

tensor([[9.8974e-08, 0.0000e+00, 1.0822e-07],
        [0.0000e+00, 1.1210e-43, 0.0000e+00]])

In [27]:
# Check type
type(a)

torch.Tensor

In [10]:
# Using Zeros:- All values set to 0
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [19]:
# Using Ones:- All values set to 1
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [20]:
# Using of rand:- Returns a 2×3 tensor with random values uniformly sampled from [0, 1).
torch.rand(2,3)

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [21]:
# Manual Seed:- Sets the seed for generating random numbers to ensure reproducibility.
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [29]:
# Using Tensor:-  constructs a tensor from a Python list or nested list (or NumPy array).
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [31]:
# Other ways to create a Tensor

# Arange:- Creates a 1D tensor with values from 0 to 8, spaced by 2.
print("Using arange:-\n",torch.arange(0,10,2))

# Using Linspace:- Creates a 1D tensor of 10 evenly spaced values between 0 and 10 (inclusive).
print("Using linspace:- \n",torch.linspace(0,10,10))

# Using eye:- Creates a 5×5 identity matrix (diagonal = 1, others = 0).
print("Using eye:- \n",torch.eye(5))

# Using Full:- Creates a 2×3 tensor filled with the constant value 5
print("Using Full:- \n",torch.full((2,3),5))

Using arange:-
 tensor([0, 2, 4, 6, 8])
Using linspace:- 
 tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
Using eye:- 
 tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Using Full:- 
 tensor([[5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [32]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [33]:
x.shape

torch.Size([2, 3])

In [35]:
# Using empty_like:- Creates a new tensor with the same shape and type as x, but with uninitialized (garbage) values.
torch.empty_like(x)

tensor([[869983213,         5,         5],
        [        5,         5,         5]])

In [36]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [37]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [40]:
# Attempts to create a tensor with random values (uniformly in [0, 1)) matching the shape of x, but throws an error if x has integer type (like Long), because random floats cannot be stored in integer tensors.
# Because rand generate by default float value so its give error
torch.rand_like(x,dtype=torch.float32)


tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

## Tensor Data Types

In [42]:
# Find Data Type
x.dtype

torch.int64

In [43]:
# Assign Data Type
torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [45]:
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [48]:
# Using to() to change data type
x.to(dtype=torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |
# **bold text**

## Mathematical Operations

## 1. Scalar Operation

In [49]:
x=torch.rand(2,2)
x

tensor([[0.2239, 0.3023],
        [0.1784, 0.8238]])

In [55]:
# Addition
print("Adding 2 to x:-\n",x+2)

# Substraction
print("Subtract 2 to x:-\n",x-2)

# Multiplication
print("Multiply 2 to x:-\n",x*2)

# Division
print("Divide 2 to x:-\n",x/2)

# int division
print("int divide 2 to x:-\n",(x*100)//2)

# Mod
print("Mod 2 to x:-\n",((x*100)//2)%2)

# Power
print("Power 2 to x:-\n",x**2)


Adding 2 to x:-
 tensor([[2.2239, 2.3023],
        [2.1784, 2.8238]])
Subtract 2 to x:-
 tensor([[-1.7761, -1.6977],
        [-1.8216, -1.1762]])
Multiply 2 to x:-
 tensor([[0.4478, 0.6047],
        [0.3568, 1.6477]])
Divide 2 to x:-
 tensor([[0.1119, 0.1512],
        [0.0892, 0.4119]])
int divide 2 to x:-
 tensor([[11., 15.],
        [ 8., 41.]])
Mod 2 to x:-
 tensor([[1., 1.],
        [0., 1.]])
Power 2 to x:-
 tensor([[0.0501, 0.0914],
        [0.0318, 0.6787]])


## 2. Element wise Operation

In [56]:
a=torch.rand(2,3)
b=torch.rand(2,3)

print(a)
print(b)

tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])
tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])


In [58]:
# Addition of two tensor
print("Adding two tensor a & b:-\n",a+b)

# Substraction
print("Subtract two tensor a & b:-\n",a-b)

# Multiplication
print("Multiply teo tensor a & b:-\n",a*b)

# Division
print("Divide two tenor a & b:-\n",a/b)

# Mod
print("Mod of two tensor a & b:-\n",a%b)

# Power
print("Power of two tensor a & b:-\n",a**b)


Adding two tensor a & b:-
 tensor([[0.7983, 1.6774, 0.9717],
        [1.1950, 1.5354, 0.9127]])
Subtract two tensor a & b:-
 tensor([[ 0.3132,  0.2767, -0.0837],
        [ 0.7007, -0.0464,  0.0657]])
Multiply teo tensor a & b:-
 tensor([[0.1348, 0.6842, 0.2343],
        [0.2343, 0.5888, 0.2072]])
Divide two tenor a & b:-
 tensor([[2.2912, 1.3951, 0.8415],
        [3.8346, 0.9413, 1.1552]])
Mod of two tensor a & b:-
 tensor([[0.0706, 0.2767, 0.4440],
        [0.2063, 0.7445, 0.0657]])
Power of two tensor a & b:-
 tensor([[0.8672, 0.9839, 0.6515],
        [0.9868, 0.7919, 0.7388]])


In [59]:
c=torch.tensor([1,-2,-5,6])
c

tensor([ 1, -2, -5,  6])

In [62]:
# abs value
abs(c)  # Pythono built-in method
torch.abs(c) # torch method

tensor([1, 2, 5, 6])

In [64]:
# convert negative number
torch.neg(c) # negative become positive and p[ositive become negative

tensor([-1,  2,  5, -6])

In [70]:
d=torch.tensor([1.5,2.6,3.2,4.1])
d

tensor([1.5000, 2.6000, 3.2000, 4.1000])

In [71]:
# round off number Rounds each element of d to the nearest integer (rounds .5 to even).
torch.round(d)

tensor([2., 3., 3., 4.])

In [72]:
# Ceil Rounds each element of d upward to the nearest integer.
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [74]:
# floor Rounds each element of tensor d downward to the nearest integer (i.e., the largest integer ≤ the value).
torch.floor(d)

tensor([1., 2., 3., 4.])

In [77]:
# clamp Clamps all elements in tensor d to lie within the range [2, 3], replacing values below 2 with 2 and above 3 with 3.
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.6000, 3.0000, 3.0000])

## 3. Reduction Operation

In [79]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[5., 7., 5.],
        [9., 9., 7.]])

In [84]:
# sum
print("Sum:- \n",torch.sum(e))

# sum along column
print("Sum:- \n",torch.sum(e,dim=0))

# sum along rows
print("Sum:- \n",torch.sum(e,dim=1))

Sum:- 
 tensor(42.)
Sum:- 
 tensor([14., 16., 12.])
Sum:- 
 tensor([17., 25.])


In [86]:
# mean
print('Mean:-\n',torch.mean(e))

# mean along column
print('Mean:-\n',torch.mean(e,dim=0))

Mean:-
 tensor(7.)
Mean:-
 tensor([7., 8., 6.])


In [87]:
# median
torch.median(e)

tensor(7.)

In [88]:
# Max
print("Max:-\n",torch.max(e))

# Min
print('Min:-\n',torch.min(e))

Max:-
 tensor(9.)
Min:-
 tensor(5.)


In [90]:
# Product
torch.prod(e)

tensor(99225.)

In [91]:
# Standard Deviations
torch.std(e)

tensor(1.7889)

In [94]:
# Variance
torch.var(e)

tensor(3.2000)

In [95]:
# argmax give position of maximum value
torch.argmax(e)

tensor(3)

In [96]:
# argmin give position of min value
torch.argmin(e)

tensor(0)

## 4. Matrix Operations

In [101]:
f=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
g=torch.randint(size=(3,2),low=0,high=10,dtype=torch.float32)

print(f)
print(g)

tensor([[8., 3., 3.],
        [5., 0., 6.]])
tensor([[4., 0.],
        [8., 4.],
        [7., 2.]])


In [102]:
# Matrix Multiplication
torch.matmul(f,g)

tensor([[77., 18.],
        [62., 12.]])

In [103]:
vector1=torch.tensor([1,2])
vector2=torch.tensor([3,4])

# dot product
torch.dot(vector1,vector2)

tensor(11)

In [110]:
# Transpose Returns a new tensor with dimensions 0 and 1 swapped (i.e., transposes rows and columns of 2D tensor f).
print(f)
torch.transpose(f,1,0)

tensor([[8., 3., 3.],
        [5., 0., 6.]])


tensor([[8., 5.],
        [3., 0.],
        [3., 6.]])

In [113]:
h=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
h

tensor([[3., 8., 5.],
        [6., 2., 9.],
        [5., 0., 4.]])

In [114]:
# Determinant
torch.det(h)

tensor(142.)

In [115]:
# Inverse Returns the inverse of a square, non-singular matrix h (i.e., a matrix such that h × h⁻¹ = I).
torch.inverse(h)

tensor([[ 0.0563, -0.2254,  0.4366],
        [ 0.1479, -0.0915,  0.0211],
        [-0.0704,  0.2817, -0.2958]])

## 5. Comparision Operations

In [116]:
i=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
j=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)

print(i)
print(j)

tensor([[2., 7., 1.],
        [1., 5., 4.]])
tensor([[4., 1., 1.],
        [2., 4., 7.]])


In [118]:
# greater than
print(i > j)
# less than
print(i < j)
# equal to
print(i == j)
# not equal to
print(i != j)
# greater than equal to
print(i<=j)
# less than equal to
print(i>=j)

tensor([[False,  True, False],
        [False,  True, False]])
tensor([[ True, False, False],
        [ True, False,  True]])
tensor([[False, False,  True],
        [False, False, False]])
tensor([[ True,  True, False],
        [ True,  True,  True]])
tensor([[ True, False,  True],
        [ True, False,  True]])
tensor([[False,  True,  True],
        [False,  True, False]])


## 6. Special Function

In [122]:
k=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
k

tensor([[2., 5., 6.],
        [1., 4., 5.]])

In [123]:
# Log
torch.log(k)

tensor([[0.6931, 1.6094, 1.7918],
        [0.0000, 1.3863, 1.6094]])

In [124]:
# Exp
torch.exp(k)

tensor([[  7.3891, 148.4132, 403.4288],
        [  2.7183,  54.5981, 148.4132]])

In [125]:
# SQRT
torch.sqrt(k)

tensor([[1.4142, 2.2361, 2.4495],
        [1.0000, 2.0000, 2.2361]])

In [126]:
# Sigmoid
torch.sigmoid(k)

tensor([[0.8808, 0.9933, 0.9975],
        [0.7311, 0.9820, 0.9933]])

In [129]:
# Softmax Applies the softmax function along dimension 0, turning values into probabilities that sum to 1 along that dimension.
torch.softmax(k,dim=0)

tensor([[0.7311, 0.7311, 0.7311],
        [0.2689, 0.2689, 0.2689]])

In [130]:
# Relu
torch.relu(k)

tensor([[2., 5., 6.],
        [1., 4., 5.]])

## 7. Inplace Operations.

In [131]:
m=torch.rand(2,3)
n=torch.rand(2,3)
print(m)
print(n)

tensor([[0.9157, 0.3079, 0.6269],
        [0.8277, 0.6594, 0.0887]])
tensor([[0.4890, 0.5887, 0.7340],
        [0.8497, 0.9112, 0.4847]])


In [136]:
# # Performs in-place addition of tensor n to tensor m, modifying m directly without creating a new tensor.

# 🔁 Difference:
# m.add(n) → returns a new tensor
# m.add_(n) → updates m in-place
m.add_(n)

tensor([[2.3826, 2.0741, 2.8290],
        [3.3768, 3.3929, 1.5429]])

In [134]:
m

tensor([[1.8937, 1.4854, 2.0950],
        [2.5271, 2.4817, 1.0582]])

In [135]:
n

tensor([[0.4890, 0.5887, 0.7340],
        [0.8497, 0.9112, 0.4847]])

## 8. Copying a Tensor

# x.clone(): Creates a new, independent copy of the tensor with separate memory.

# y = x: Only creates a reference to the same tensor; changing y also changes x.

In [137]:
a=torch.rand(2,3)
a

tensor([[0.9436, 0.3904, 0.2499],
        [0.3206, 0.9753, 0.7582]])

In [138]:
b=a

In [139]:
b

tensor([[0.9436, 0.3904, 0.2499],
        [0.3206, 0.9753, 0.7582]])

In [141]:
a[0][0]=7
a

tensor([[7.0000, 0.3904, 0.2499],
        [0.3206, 0.9753, 0.7582]])

In [142]:
b

tensor([[7.0000, 0.3904, 0.2499],
        [0.3206, 0.9753, 0.7582]])

In [143]:
id(a)

140049279622736

In [144]:
id(b)

140049279622736

In [145]:
c=a.clone()
c

tensor([[7.0000, 0.3904, 0.2499],
        [0.3206, 0.9753, 0.7582]])

In [147]:
a[0][0]=12
a

tensor([[12.0000,  0.3904,  0.2499],
        [ 0.3206,  0.9753,  0.7582]])

In [148]:
c

tensor([[7.0000, 0.3904, 0.2499],
        [0.3206, 0.9753, 0.7582]])

In [149]:
id(a)

140049279622736

In [150]:
id(c)

140054071244464