### Training pipe line using NN modules.

## Important Library.

In [3]:
# pip install torchinfo

In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.datasets import load_breast_cancer
import torch 
import torch.nn as nn
from torchinfo import summary

## Define Model.

In [121]:
# Create Model Class with simple neural network without hidden layers.
class Model(nn.Module):
    def __init__(self, num_features):
        
        super().__init__()
        
        self.linear=nn.Linear(num_features,1)
        self.sigmoid=nn.Sigmoid()
    
# Forward Pass
    def forward(self,features):
        
        out=self.linear(features)
        out=self.sigmoid(out)
        
        return out

# Create fake dataset.
features=torch.rand(10,5)
print(features.shape)

# Create Model object.
model=Model(features.shape[1])

# Call forward pass.
#model.forward(features) # pytorch used magic method __call__ and override  this and when we call its autometic trigger.
model(features)

# show model weights and bias.
print(model.linear.weight)
print(model.linear.bias)

print(summary(model,input_size=(10,5)))

torch.Size([10, 5])
Parameter containing:
tensor([[ 0.4158, -0.3820, -0.2416,  0.0510, -0.3105]], requires_grad=True)
Parameter containing:
tensor([0.0604], requires_grad=True)
Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00


In [10]:
# Create Model Class with simple neural network with hidden layers.
class Model(nn.Module):
    def __init__(self, num_features):
        
        super().__init__()
        
        self.linear1=nn.Linear(num_features,3)
        self.relu=nn.ReLU()
        self.linear2=nn.Linear(3,1)
        self.sigmoid=nn.Sigmoid()
    
# Forward Pass
    def forward(self,features):
        
        out=self.linear1(features)
        out=self.relu(out)
        out=self.linear2(out)
        out=self.sigmoid(out)
        
        return out

# Create fake dataset.
features=torch.rand(10,5)

# Create Model object.
model=Model(features.shape[1])

# Call forward pass.
#model.forward(features) # pytorch used magic method __call__ and override  this and when we call its autometic trigger.
model(features)

# show model weights and bias.
print(model.linear1.weight)
print(model.linear1.bias)
print(model.linear2.weight)
print(model.linear2.bias)

print(summary(model,input_size=(10,5)))

Parameter containing:
tensor([[ 0.2530, -0.3997, -0.0632,  0.1510, -0.0385],
        [ 0.1416,  0.2036, -0.1634, -0.4263, -0.2696],
        [-0.3738, -0.2034, -0.2498,  0.1593, -0.0446]], requires_grad=True)
Parameter containing:
tensor([ 0.2746,  0.3960, -0.1268], requires_grad=True)
Parameter containing:
tensor([[-0.1425,  0.1777,  0.1250]], requires_grad=True)
Parameter containing:
tensor([0.4779], requires_grad=True)
Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size 

In [12]:
# Create Model Class with simple neural network with hidden layers and use sequential container.
class Model(nn.Module):
    def __init__(self, num_features):
        
        super().__init__()
        
        self.network=nn.Sequential(nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )
    
# Forward Pass
    def forward(self,features):
        
        out=self.network(features)  
        return out

# Create fake dataset.
features=torch.rand(10,5)

# Create Model object.
model=Model(features.shape[1])

# Call forward pass.
#model.forward(features) # pytorch used magic method __call__ and override  this and when we call its autometic trigger.
model(features)

# Iterate through each layer and print its parameters
for name, param in model.named_parameters():
    if 'weight' in name:
        print(f'Layer: {name} | Size: {param.size()} | Values: {param}\n')
    elif 'bias' in name:
        print(f'Layer: {name} | Size: {param.size()} | Values: {param}\n')

print(summary(model,input_size=(10,5)))

Layer: network.0.weight | Size: torch.Size([3, 5]) | Values: Parameter containing:
tensor([[ 0.1004, -0.1478, -0.0462, -0.4153,  0.0950],
        [-0.2977, -0.0104, -0.1724,  0.2615,  0.0189],
        [ 0.0158,  0.1700, -0.1978,  0.3707,  0.1917]], requires_grad=True)

Layer: network.0.bias | Size: torch.Size([3]) | Values: Parameter containing:
tensor([0.2534, 0.0745, 0.0961], requires_grad=True)

Layer: network.2.weight | Size: torch.Size([1, 3]) | Values: Parameter containing:
tensor([[-0.3534,  0.2422,  0.1602]], requires_grad=True)

Layer: network.2.bias | Size: torch.Size([1]) | Values: Parameter containing:
tensor([-0.0026], requires_grad=True)

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]      

## Load data, Split data, Scale data, Encode data.

In [134]:
df = load_breast_cancer()
X = df.data
y = df.target

# Train Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, test_size=0.2)

# Scaling
sc = StandardScaler()
X_train_new = sc.fit_transform(X_train)
X_test_new = sc.transform(X_test)

# Encoding target
lenc = LabelEncoder()
y_train_new = lenc.fit_transform(y_train)
y_test_new = lenc.transform(y_test)

## Convert Numpy to Tensor array.

In [137]:
# Numpy array to tensor 
X_train = torch.from_numpy(X_train_new).float()
X_test = torch.from_numpy(X_test_new).float()
y_train = torch.from_numpy(y_train_new).float()
y_test = torch.from_numpy(y_test_new).float()

## Define Model.

In [140]:
# Create Model.
class MySimpleModel(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network=nn.Sequential(nn.Linear(num_features,20),
                                  nn.ReLU(),
                                  nn.Linear(20,15),
                                  nn.ReLU(),
                                  nn.Linear(15,10),
                                  nn.ReLU(),
                                  nn.Linear(10,1),
                                  nn.Sigmoid()
                                  )
    def forward(self,features):
        out=self.network(features)
        return out

## Important Parameters.

In [143]:
learning_rate=0.1
epochs=25

## Training Pipeline.

In [146]:
# Define Loss Function.
loss_func=nn.BCELoss()

# Create Model Object.
model= MySimpleModel(X_train.shape[1])

# Define optimizer.
optimizer= torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loop
for epoch in range(epochs):

    # forward pass
    y_pred=model(X_train)
    
    # Loss calculation
    # view() is used to reshape a tensor without changing its data. 
    # The -1 tells PyTorch: "I don’t know what this dimension should be,
    # so calculate it automatically based on the other dimensions and total number of elements.""""
    loss=loss_func(y_pred, y_train.view(-1,1))
    
    # Clear gradients 
    optimizer.zero_grad()

    # Backward pass
    loss.backward()
    
    #parameters update
    optimizer.step()
    
    # print loss in each epoch
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

    

Epoch: 1, Loss: 0.7047147750854492
Epoch: 2, Loss: 0.7004538178443909
Epoch: 3, Loss: 0.6964207887649536
Epoch: 4, Loss: 0.6925965547561646
Epoch: 5, Loss: 0.6889612078666687
Epoch: 6, Loss: 0.6854921579360962
Epoch: 7, Loss: 0.68217533826828
Epoch: 8, Loss: 0.6789976954460144
Epoch: 9, Loss: 0.6759387254714966
Epoch: 10, Loss: 0.6729825735092163
Epoch: 11, Loss: 0.6701138615608215
Epoch: 12, Loss: 0.667317807674408
Epoch: 13, Loss: 0.6645802855491638
Epoch: 14, Loss: 0.66189044713974
Epoch: 15, Loss: 0.6592341661453247
Epoch: 16, Loss: 0.6566019058227539
Epoch: 17, Loss: 0.653978168964386
Epoch: 18, Loss: 0.6513524055480957
Epoch: 19, Loss: 0.6487146615982056
Epoch: 20, Loss: 0.6460612416267395
Epoch: 21, Loss: 0.643376886844635
Epoch: 22, Loss: 0.6406514048576355
Epoch: 23, Loss: 0.6378569006919861
Epoch: 24, Loss: 0.634980320930481
Epoch: 25, Loss: 0.6320151090621948


## Evaluation.

In [157]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6315789222717285


In [159]:
print(summary(model, input_size=(X_train.shape[0], X_train.shape[1])))

Layer (type:depth-idx)                   Output Shape              Param #
MySimpleModel                            [455, 1]                  --
├─Sequential: 1-1                        [455, 1]                  --
│    └─Linear: 2-1                       [455, 20]                 620
│    └─ReLU: 2-2                         [455, 20]                 --
│    └─Linear: 2-3                       [455, 15]                 315
│    └─ReLU: 2-4                         [455, 15]                 --
│    └─Linear: 2-5                       [455, 10]                 160
│    └─ReLU: 2-6                         [455, 10]                 --
│    └─Linear: 2-7                       [455, 1]                  11
│    └─Sigmoid: 2-8                      [455, 1]                  --
Total params: 1,106
Trainable params: 1,106
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.50
Input size (MB): 0.05
Forward/backward pass size (MB): 0.17
Params size (MB): 0.00
Estimated Total Size (MB): 0.23