# TensorFlow 2.x

Tensorflow :- 
- Constant Tensor Array [Immutable Tensor Array]
- Variable Tensor Array [Mutable Tensor Array]
- pip install tensorflow

In [1]:
import tensorflow as tf

In [134]:
tf.__version__

'2.16.1'

# How to Create Constant Tensor Array.

- tf.constant(value,dtype,shape,name)
- zero dimension tensor array/zero rank tensor array

In [135]:
a=tf.constant(10)
a

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [136]:
b=tf.constant(20)
b

<tf.Tensor: shape=(), dtype=int32, numpy=20>

In [137]:
c=a+b
c

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [138]:
type(c)

tensorflow.python.framework.ops.EagerTensor

In [139]:
a=tf.constant(20.5)
a

<tf.Tensor: shape=(), dtype=float32, numpy=20.5>

In [140]:
b=tf.constant(40.5)
b

<tf.Tensor: shape=(), dtype=float32, numpy=40.5>

In [141]:
c=a+b
c

<tf.Tensor: shape=(), dtype=float32, numpy=61.0>

In [142]:
a=tf.constant('Welcome to tensorflow')
a

<tf.Tensor: shape=(), dtype=string, numpy=b'Welcome to tensorflow'>

In [143]:
a.dtype

tf.string

In [144]:
a=tf.constant(3+4j)
a

<tf.Tensor: shape=(), dtype=complex128, numpy=(3+4j)>

In [145]:
a=tf.constant(True)
a

<tf.Tensor: shape=(), dtype=bool, numpy=True>

# How to create Constant Tensor Array Using List,Nested List, Numpy Array.

- 1-dimension tensor array

In [146]:
a=tf.constant([2,3,4,5,6,7])
a

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([2, 3, 4, 5, 6, 7])>

In [147]:
a.dtype

tf.int32

In [148]:
a.shape

TensorShape([6])

In [149]:
type(a)

tensorflow.python.framework.ops.EagerTensor

In [150]:
b=a.numpy()
b

array([2, 3, 4, 5, 6, 7])

In [151]:
type(b)

numpy.ndarray

In [152]:
b=a.numpy()[3:]
b

array([5, 6, 7])

In [153]:
print(a[2])

tf.Tensor(4, shape=(), dtype=int32)


In [155]:
c=a.numpy().tolist()
c

[2, 3, 4, 5, 6, 7]

In [156]:
type(c)

list

In [157]:
a=tf.constant([2,3,4,5],dtype=tf.float32)
a

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([2., 3., 4., 5.], dtype=float32)>

In [158]:
a=tf.constant([2,3,4,5],dtype='float',shape=(2,2))
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [4., 5.]], dtype=float32)>

In [159]:
a.shape

TensorShape([2, 2])

In [160]:
a.dtype

tf.float32

In [161]:
type(a)

tensorflow.python.framework.ops.EagerTensor

In [2]:
a=tf.constant([2,3,4,5,6,7],dtype=tf.float32)
a

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([2., 3., 4., 5., 6., 7.], dtype=float32)>

In [3]:
a=tf.constant([2,3,4,5],dtype=tf.float32,shape=(2,2))
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [4., 5.]], dtype=float32)>

In [4]:
a=tf.constant([[2,3],[1,4],[3,5],[6,7]],dtype=tf.float64)
a 

<tf.Tensor: shape=(4, 2), dtype=float64, numpy=
array([[2., 3.],
       [1., 4.],
       [3., 5.],
       [6., 7.]])>

In [5]:
type(a)

tensorflow.python.framework.ops.EagerTensor

In [6]:
a.numpy()

array([[2., 3.],
       [1., 4.],
       [3., 5.],
       [6., 7.]])

In [7]:
a.numpy().tolist()

[[2.0, 3.0], [1.0, 4.0], [3.0, 5.0], [6.0, 7.0]]

In [8]:
a.numpy()[1,1]

4.0

In [9]:
a.numpy()[:,1:2]

array([[3.],
       [4.],
       [5.],
       [7.]])

In [10]:
a=tf.constant([[[2,3],[4,5],[5,6]]],dtype=tf.float32)
a

<tf.Tensor: shape=(1, 3, 2), dtype=float32, numpy=
array([[[2., 3.],
        [4., 5.],
        [5., 6.]]], dtype=float32)>

In [11]:
a.shape

TensorShape([1, 3, 2])

In [12]:
a[0][1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4., 5.], dtype=float32)>

In [13]:
a[0][-2]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4., 5.], dtype=float32)>

In [14]:
import numpy as np
a=tf.constant(np.array([2,3,4]))
a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4])>

In [15]:
a=tf.constant(np.array([[2,3,4],[5,6,7],[8,9,3]]))
a

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [5, 6, 7],
       [8, 9, 3]])>

In [17]:
a=tf.constant(np.array([[[2,3],[4,5],[6,7]]]),dtype=tf.float32)
a

<tf.Tensor: shape=(1, 3, 2), dtype=float32, numpy=
array([[[2., 3.],
        [4., 5.],
        [6., 7.]]], dtype=float32)>

# Mathematical Operation in Constant Tensor Array.

In [18]:
a=tf.constant([[2,3],[5,6]],tf.float32)
b=tf.constant ([[4,5],[7,8]],tf.float32)
c=tf.add(a,b)
print(c)

tf.Tensor(
[[ 6.  8.]
 [12. 14.]], shape=(2, 2), dtype=float32)


In [19]:
d=tf.subtract(a,b)
d

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-2., -2.],
       [-2., -2.]], dtype=float32)>

In [20]:
e=tf.multiply(a,b)
e

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 8., 15.],
       [35., 48.]], dtype=float32)>

In [21]:
f=tf.divide(a,b)
f

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.5       , 0.6       ],
       [0.71428573, 0.75      ]], dtype=float32)>

In [22]:
x=tf.matmul(a,b)#Dot Product
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[29., 34.],
       [62., 73.]], dtype=float32)>

In [23]:
print(a@b) # Dot Product

tf.Tensor(
[[29. 34.]
 [62. 73.]], shape=(2, 2), dtype=float32)


In [50]:
print(tf.random.normal([10]))

tf.Tensor(
[ 0.42156577 -0.19106314 -1.1716601  -0.23518945  0.7591955   0.282994
 -1.1531141  -1.2819446   0.31560653  0.37977415], shape=(10,), dtype=float32)


In [51]:
print(tf.random.uniform([10]))

tf.Tensor(
[0.6359643  0.01085079 0.54482234 0.36937833 0.6728399  0.15904105
 0.62557685 0.08191609 0.64818525 0.19445813], shape=(10,), dtype=float32)


In [52]:
print(tf.random.uniform([50],minval=1,maxval=5,dtype=tf.int32))

tf.Tensor(
[1 4 2 1 1 3 3 1 4 3 2 3 1 1 4 3 4 1 1 3 3 4 3 4 2 4 3 3 3 1 4 1 3 3 2 1 1
 1 3 4 2 4 3 3 1 1 1 3 3 2], shape=(50,), dtype=int32)


In [24]:
print(tf.random.uniform([100],minval=1,maxval=10,dtype=tf.int32))

tf.Tensor(
[1 9 9 4 3 3 6 5 8 1 1 4 3 2 2 7 1 9 3 8 4 6 3 2 7 5 3 9 7 9 1 2 4 8 1 1 2
 2 9 1 6 3 3 7 2 2 5 7 4 9 8 1 8 9 8 8 8 2 9 2 5 8 5 3 4 8 7 8 2 3 3 2 8 5
 8 3 7 3 2 3 1 7 7 3 7 1 8 7 8 4 7 3 5 1 4 4 9 4 1 4], shape=(100,), dtype=int32)


In [25]:
x=tf.random.uniform([10],minval=1,maxval=100,dtype=tf.int32)
x

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([23, 83, 86, 87, 89, 73, 48, 99, 39, 78])>

In [26]:
print(tf.math.reduce_sum(x))

tf.Tensor(705, shape=(), dtype=int32)


In [27]:
print(tf.math.reduce_min(x))

tf.Tensor(23, shape=(), dtype=int32)


In [28]:
print(tf.math.reduce_max(x))

tf.Tensor(99, shape=(), dtype=int32)


In [29]:
print(tf.math.reduce_mean(x))

tf.Tensor(70, shape=(), dtype=int32)


In [30]:
print(tf.math.argmax(x))

tf.Tensor(7, shape=(), dtype=int64)


In [32]:
print(tf.math.argmin(x))

tf.Tensor(0, shape=(), dtype=int64)


# Variable Tensor Array :- (Mutable Tensor Array).

In [33]:
import tensorflow as tf

- tf.Variable(value,dtype,shape,name)

In [34]:
a=tf.Variable(10)
a

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>

In [35]:
type(a)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [36]:
x=tf.Variable([2,3,4,5])
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([2, 3, 4, 5])>

In [37]:
type(x)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [38]:
x.shape

TensorShape([4])

In [39]:
x.dtype

tf.int32

In [40]:
x.name

'Variable:0'

In [41]:
x=tf.Variable([2.,3.,4.5,5.6],name='Vector')
x

<tf.Variable 'Vector:0' shape=(4,) dtype=float32, numpy=array([2. , 3. , 4.5, 5.6], dtype=float32)>

In [42]:
x.name

'Vector:0'

In [43]:
x=tf.Variable(['a','b','c','d'])
x

<tf.Variable 'Variable:0' shape=(4,) dtype=string, numpy=array([b'a', b'b', b'c', b'd'], dtype=object)>

In [44]:
x.dtype

tf.string

In [45]:
x=tf.Variable([True,False])
x

<tf.Variable 'Variable:0' shape=(2,) dtype=bool, numpy=array([ True, False])>

In [46]:
x=tf.Variable([3+6j])
x

<tf.Variable 'Variable:0' shape=(1,) dtype=complex128, numpy=array([3.+6.j])>

In [47]:
x.dtype

tf.complex128

In [48]:
x=tf.Variable([2,3,4,5,6],dtype=tf.float32)
x

<tf.Variable 'Variable:0' shape=(5,) dtype=float32, numpy=array([2., 3., 4., 5., 6.], dtype=float32)>

In [49]:
type(x)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [50]:
x.assign([5,9,8,7,6])
x

<tf.Variable 'Variable:0' shape=(5,) dtype=float32, numpy=array([5., 9., 8., 7., 6.], dtype=float32)>

In [51]:
a=tf.constant([2,3,4,5,6])
a

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([2, 3, 4, 5, 6])>

In [52]:
type(a)

tensorflow.python.framework.ops.EagerTensor

In [53]:
# a.assign([2,3,8,9,10])

In [54]:
x=tf.Variable([2,3,4,5,6],dtype=tf.float32)
x

<tf.Variable 'Variable:0' shape=(5,) dtype=float32, numpy=array([2., 3., 4., 5., 6.], dtype=float32)>

In [55]:
type(x)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [56]:
# x.assign([2,5,6,7,8,9]) # Equal len is modify only and same shape is modify different type is not modify)

In [57]:
x.assign_add([1,2,3,4,5])
x

<tf.Variable 'Variable:0' shape=(5,) dtype=float32, numpy=array([ 3.,  5.,  7.,  9., 11.], dtype=float32)>

In [58]:
x.assign_sub([1,2,3,4,5])
x

<tf.Variable 'Variable:0' shape=(5,) dtype=float32, numpy=array([2., 3., 4., 5., 6.], dtype=float32)>

In [59]:
a=tf.constant([[2,3],[4,5],[9,6]])
a

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5],
       [9, 6]])>

In [60]:
type(a)

tensorflow.python.framework.ops.EagerTensor

In [61]:
x=tf.Variable(a) # Change constant array to Variable array
x

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[2, 3],
       [4, 5],
       [9, 6]])>

In [62]:
type(x)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [63]:
x.numpy()

array([[2, 3],
       [4, 5],
       [9, 6]])

In [64]:
tf.argmax(x)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([2, 2], dtype=int64)>

In [65]:
tf.argmax(x).numpy()

array([2, 2], dtype=int64)

In [66]:
tf.argmin(x)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([0, 0], dtype=int64)>

In [67]:
tf.argmin(x).numpy()

array([0, 0], dtype=int64)

In [68]:
x=tf.Variable([2,3,4,5],dtype=tf.float32)
x

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([2., 3., 4., 5.], dtype=float32)>

In [69]:
b=tf.reshape(x,(2,2))
b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [4., 5.]], dtype=float32)>

In [70]:
type(b)

tensorflow.python.framework.ops.EagerTensor

In [71]:
x=tf.Variable([[2,3],[4,5],[5,6]])
x

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[2, 3],
       [4, 5],
       [5, 6]])>

In [72]:
type(x)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [73]:
y=tf.convert_to_tensor(x)
y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5],
       [5, 6]])>

In [74]:
type(y)

tensorflow.python.framework.ops.EagerTensor

In [75]:
x=tf.ones(10,dtype=tf.int32)
print(x)

tf.Tensor([1 1 1 1 1 1 1 1 1 1], shape=(10,), dtype=int32)


In [76]:
x=tf.ones((3,2),dtype=tf.int32)
print(x)

tf.Tensor(
[[1 1]
 [1 1]
 [1 1]], shape=(3, 2), dtype=int32)


In [77]:
x=tf.ones((2,3,2),dtype=tf.int32)
print(x)

tf.Tensor(
[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]], shape=(2, 3, 2), dtype=int32)


In [78]:
x.shape

TensorShape([2, 3, 2])

In [79]:
type(x)

tensorflow.python.framework.ops.EagerTensor

In [80]:
# tf.ones_Like() 
x=tf.constant([[2,3],[4,5],[6,7]],dtype=tf.float32)
x

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[2., 3.],
       [4., 5.],
       [6., 7.]], dtype=float32)>

In [81]:
y=tf.ones_like(x,dtype=tf.int32)
y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1],
       [1, 1]])>

In [82]:
a=tf.Variable([[[2,3,4],[4,5,6],[8,9,7]]],dtype=tf.float32)
a

<tf.Variable 'Variable:0' shape=(1, 3, 3) dtype=float32, numpy=
array([[[2., 3., 4.],
        [4., 5., 6.],
        [8., 9., 7.]]], dtype=float32)>

In [83]:
type(a)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [84]:
b=tf.ones_like(a,dtype=tf.int32)
b

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])>

In [85]:
a=tf.zeros(10)
print(a)

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)


In [86]:
b=tf.zeros((2,3),dtype=tf.int32)
print(b)

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


In [87]:
b=tf.zeros((1,3,2),dtype=tf.int32)
print(b)

tf.Tensor(
[[[0 0]
  [0 0]
  [0 0]]], shape=(1, 3, 2), dtype=int32)


In [88]:
x=tf.constant([[2,3],[4,5],[6,7]],dtype=tf.float32)
x

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[2., 3.],
       [4., 5.],
       [6., 7.]], dtype=float32)>

In [89]:
y=tf.zeros_like(x)
y

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [90]:
a=tf.fill((3,2),9)
a

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[9, 9],
       [9, 9],
       [9, 9]])>

In [91]:
type(a)

tensorflow.python.framework.ops.EagerTensor

In [92]:
b=tf.fill((3,3),2.5)
b

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5]], dtype=float32)>

In [93]:
c=tf.eye(2)
c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.]], dtype=float32)>

In [94]:
c=tf.eye(3,2)
c

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.],
       [0., 0.]], dtype=float32)>

In [95]:
d=tf.eye(3,3,dtype=tf.int32,batch_shape=[3])
d

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]],

       [[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]],

       [[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]]])>

In [96]:
d=tf.eye(3,3,dtype=tf.int32,batch_shape=[2])
d

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]],

       [[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]]])>